/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/lee/nim_projects/number_place/nimcache/math.o /home/lee/nim_projects/number_place/nimcache/math.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <stdlib.h>
typedef struct Runningstat143669 Runningstat143669;
struct  Runningstat143669  {
NI n;
NF sum;
NF min;
NF max;
NF mean;
NF oldm;
NF olds;
NF news;
};
N_NIMCALL(NI, binom_141208)(NI n, NI k);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, fac_141248)(NI n);
N_NIMCALL(NU8, classify_141626)(NF x);
N_NIMCALL(NIM_BOOL, ispoweroftwo_141638)(NI x);
N_NIMCALL(NI, nextpoweroftwo_141648)(NI x);
N_NIMCALL(NI, countbits32_142225)(NI32 n);
N_NIMCALL(NF, log2_142425)(NF x);
N_NIMCALL(NF, random_142335)(NF max);
N_NIMCALL(void, randomize_142341)(void);
N_NIMCALL(void, randomize_142404)(NI seed);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI, random_142329)(NI max);
N_NIMCALL(NF, mod_143629)(NF x, NF y);
N_NIMCALL(void, push_143686)(Runningstat143669* s, NF x);
N_NIMCALL(void, push_143706)(Runningstat143669* s, NI x);
N_NIMCALL(NF, variance_143717)(Runningstat143669* s);
N_NIMCALL(NF, standarddeviation_143727)(Runningstat143669* s);
extern TFrame* frameptr_20842;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(NI, binom_141208)(NI n, NI k) {
	NI result;
	nimfr("binom", "math.nim")
{	result = 0;
	nimln(26, "math.nim");
	{
		if (!(k <= ((NI) 0))) goto LA3;
		result = ((NI) 1);
		goto BeforeRet;
	}
	LA3: ;
	nimln(27, "math.nim");
	{
		NI TMP529;
		NI TMP530;
		nimln(357, "system.nim");
		nimln(27, "math.nim");
		TMP529 = mulInt(((NI) 2), k);
		if (!(n < (NI)(TMP529))) goto LA7;
		TMP530 = subInt(n, k);
		result = binom_141208(n, (NI)(TMP530));
		goto BeforeRet;
	}
	LA7: ;
	nimln(28, "math.nim");
	result = n;
	{
		NI i_141225;
		NI res_141229;
		i_141225 = 0;
		nimln(1874, "system.nim");
		res_141229 = ((NI) 2);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP531;
				NI TMP532;
				NI TMP533;
				NI TMP534;
				NI TMP535;
				if (!(res_141229 <= k)) goto LA11;
				nimln(1876, "system.nim");
				i_141225 = res_141229;
				nimln(30, "math.nim");
				TMP531 = addInt(n, ((NI) 1));
				TMP532 = subInt((NI)(TMP531), i_141225);
				TMP533 = mulInt(result, (NI)(TMP532));
				TMP534 = divInt((NI)(TMP533), i_141225);
				result = (NI)(TMP534);
				nimln(1890, "system.nim");
				TMP535 = addInt(res_141229, ((NI) 1));
				res_141229 = (NI)(TMP535);
			} LA11: ;
		}
	}
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fac_141248)(NI n) {
	NI result;
	nimfr("fac", "math.nim")
	result = 0;
	nimln(34, "math.nim");
	result = ((NI) 1);
	{
		NI i_141264;
		NI res_141268;
		i_141264 = 0;
		nimln(1874, "system.nim");
		res_141268 = ((NI) 2);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP536;
				NI TMP537;
				if (!(res_141268 <= n)) goto LA3;
				nimln(1876, "system.nim");
				i_141264 = res_141268;
				nimln(36, "math.nim");
				TMP536 = mulInt(result, i_141264);
				result = (NI)(TMP536);
				nimln(1890, "system.nim");
				TMP537 = addInt(res_141268, ((NI) 1));
				res_141268 = (NI)(TMP537);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NU8, classify_141626)(NF x) {
	NU8 result;
{	result = 0;
	{
		if (!(x == 0.0)) goto LA3;
		{
			if (!(((NF)(1.0000000000000000e+00) / (NF)(x)) == INF)) goto LA7;
			result = ((NU8) 2);
			goto BeforeRet;
		}
		goto LA5;
		LA7: ;
		{
			result = ((NU8) 3);
			goto BeforeRet;
		}
		LA5: ;
	}
	LA3: ;
	{
		if (!(((NF)(x) * (NF)(5.0000000000000000e-01)) == x)) goto LA12;
		{
			if (!(0.0 < x)) goto LA16;
			result = ((NU8) 5);
			goto BeforeRet;
		}
		goto LA14;
		LA16: ;
		{
			result = ((NU8) 6);
			goto BeforeRet;
		}
		LA14: ;
	}
	LA12: ;
	{
		if (!!((x == x))) goto LA21;
		result = ((NU8) 4);
		goto BeforeRet;
	}
	LA21: ;
	result = ((NU8) 0);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, ispoweroftwo_141638)(NI x) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = (((NI) 0) < x);
	if (!(LOC1)) goto LA2;
	LOC1 = ((NI)(x & (NI)(x - ((NI) 1))) == ((NI) 0));
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nextpoweroftwo_141648)(NI x) {
	NI result;
	result = 0;
	result = (NI)(x - ((NI) 1));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 32))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 16))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 8))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 4))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 2))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 1))));
	result += ((NI) ((NI)(((NI) 1) + ((NI) ((x <= ((NI) 0)))))));
	return result;
}

N_NIMCALL(NI, countbits32_142225)(NI32 n) {
	NI result;
	NI32 v;
	result = 0;
	v = n;
	v = (NI32)((NU32)(v) - (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 1))) & ((NI32) 1431655765))));
	v = (NI32)((NU32)((NI32)(v & ((NI32) 858993459))) + (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 2))) & ((NI32) 858993459))));
	result = ((NI) ((NI32)((NU32)((NI32)((NU32)((NI32)((NI32)((NU32)(v) + (NU32)((NI32)((NU32)(v) >> (NU32)(((NI32) 4))))) & ((NI32) 252645135))) * (NU32)(((NI32) 16843009)))) >> (NU32)(((NI32) 24)))));
	return result;
}

N_NIMCALL(NF, log2_142425)(NF x) {
	NF result;
	NF LOC1;
	NF LOC2;
{	result = 0;
	LOC1 = 0;
	LOC1 = log(x);
	LOC2 = 0;
	LOC2 = log(2.0000000000000000e+00);
	result = ((NF)(LOC1) / (NF)(LOC2));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NF, random_142335)(NF max) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = drand48();
	result = ((NF)(LOC1) * (NF)(max));
	return result;
}

N_NIMCALL(void, randomize_142404)(NI seed) {
	srand(((int) (seed)));
	srand48(seed);
}

N_NIMCALL(void, randomize_142341)(void) {
	union { NF source; NI dest; } LOC1;
	LOC1.source = ntepochTime();
	randomize_142404(LOC1.dest);
}

N_NIMCALL(NI, random_142329)(NI max) {
	NI result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = rand();
	result = (NI)(((NI) (LOC1)) % max);
	return result;
}

N_NIMCALL(NF, mod_143629)(NF x, NF y) {
	NF result;
	result = 0;
	{
		if (!(y == 0.0)) goto LA3;
		result = x;
	}
	goto LA1;
	LA3: ;
	{
		NF LOC6;
		LOC6 = 0;
		LOC6 = floor(((NF)(x) / (NF)(y)));
		result = ((NF)(x) - (NF)(((NF)(y) * (NF)(LOC6))));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, push_143686)(Runningstat143669* s, NF x) {
	(*s).n += ((NI) 1);
	{
		if (!((*s).n == ((NI) 1))) goto LA3;
		(*s).min = x;
		(*s).max = x;
		(*s).oldm = x;
		(*s).mean = x;
		(*s).olds = 0.0;
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!(x < (*s).min)) goto LA8;
			(*s).min = x;
		}
		LA8: ;
		{
			if (!((*s).max < x)) goto LA12;
			(*s).max = x;
		}
		LA12: ;
		(*s).mean = ((NF)((*s).oldm) + (NF)(((NF)(((NF)(x) - (NF)((*s).oldm))) / (NF)(((double) ((*s).n))))));
		(*s).news = ((NF)((*s).olds) + (NF)(((NF)(((NF)(x) - (NF)((*s).oldm))) * (NF)(((NF)(x) - (NF)((*s).mean))))));
		(*s).oldm = (*s).mean;
		(*s).olds = (*s).news;
	}
	LA1: ;
	(*s).sum = ((NF)((*s).sum) + (NF)(x));
}

N_NIMCALL(void, push_143706)(Runningstat143669* s, NI x) {
	push_143686(s, ((double) (x)));
}

N_NIMCALL(NF, variance_143717)(Runningstat143669* s) {
	NF result;
	result = 0;
	{
		if (!(((NI) 1) < (*s).n)) goto LA3;
		result = ((NF)((*s).news) / (NF)(((double) ((NI)((*s).n - ((NI) 1))))));
	}
	LA3: ;
	return result;
}

N_NIMCALL(NF, standarddeviation_143727)(Runningstat143669* s) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = variance_143717(s);
	result = sqrt(LOC1);
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_mathInit000)(void) {
	nimfr("math", "math.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_mathDatInit000)(void) {
}

