/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/lee/nim_projects/number_place/nimcache/numple.o /home/lee/nim_projects/number_place/nimcache/numple.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TSafePoint TSafePoint;
typedef NI col144005[9];
typedef col144005 mtx144007[9];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY144038[2];
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19211 raiseAction;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, viewmatrix_144013)(mtx144007 matrix);
N_NIMCALL(void, write_16911)(FILE* f, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, write_16895)(FILE* f, NimStringDesc* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, checknum_144080)(mtx144007 matrix, NI row, NI col, NI num);
static N_INLINE(NF, HEX2F_90804)(NI x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_144235)(mtx144007 x, mtx144007 y);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_144425)(col144005 x, col144005 y);
N_NIMCALL(void, recursivedfs_144213)(mtx144007 m, NI row, NI col, mtx144007* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(FILE*, open_16817)(NimStringDesc* filename, NU8 mode, NI bufsize);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, readline_16916)(FILE* f);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, numpleInit000)(void);
NIM_EXTERNC N_NOINLINE(void, numpleDatInit000)(void);
STRING_LITERAL(TMP538, " ", 1);
STRING_LITERAL(TMP540, "\012", 1);
STRING_LITERAL(TMP555, "numbers.txt", 11);
STRING_LITERAL(TMP561, "finish !", 8);
extern TFrame* frameptr_20842;
extern TSafePoint* exchandler_20843;
NI i_144523;
NI j_144535;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(void, viewmatrix_144013)(mtx144007 matrix) {
	nimfr("viewMatrix", "numple.nim")
	{
		NI i_144026;
		NI res_144052;
		i_144026 = 0;
		nimln(1874, "system.nim");
		res_144052 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP541;
				if (!(res_144052 <= ((NI) 9))) goto LA3;
				nimln(1876, "system.nim");
				i_144026 = res_144052;
				{
					NI j_144037;
					NI res_144046;
					j_144037 = 0;
					nimln(1874, "system.nim");
					res_144046 = ((NI) 1);
					{
						nimln(1875, "system.nim");
						while (1) {
							TY144038 LOC7;
							NI TMP539;
							if (!(res_144046 <= ((NI) 9))) goto LA6;
							nimln(1876, "system.nim");
							j_144037 = res_144046;
							nimln(12, "numple.nim");
							memset((void*)LOC7, 0, sizeof(LOC7));
							if (i_144026 < 1 || i_144026 > 9) raiseIndexError();
							if (j_144037 < 1 || j_144037 > 9) raiseIndexError();
							LOC7[0] = nsuIntToStr(matrix[(i_144026)- 1][(j_144037)- 1], ((NI) 1));
							LOC7[1] = copyString(((NimStringDesc*) &TMP538));
							write_16911(stdout, LOC7, 2);
							nimln(1895, "system.nim");
							TMP539 = addInt(res_144046, ((NI) 1));
							res_144046 = (NI)(TMP539);
						} LA6: ;
					}
				}
				nimln(13, "numple.nim");
				write_16895(stdout, ((NimStringDesc*) &TMP540));
				nimln(1895, "system.nim");
				TMP541 = addInt(res_144052, ((NI) 1));
				res_144052 = (NI)(TMP541);
			} LA3: ;
		}
	}
	popFrame();
}

static N_INLINE(NF, HEX2F_90804)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(3124, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, checknum_144080)(mtx144007 matrix, NI row, NI col, NI num) {
	NIM_BOOL result;
	NI areax;
	NI areay;
	NF LOC15;
	NF LOC16;
	NI TMP544;
	NF LOC17;
	NF LOC18;
	NI TMP545;
	nimfr("checkNum", "numple.nim")
{	result = 0;
	nimln(17, "numple.nim");
	{
		NI i_144097;
		NI res_144140;
		i_144097 = 0;
		nimln(1874, "system.nim");
		res_144140 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP542;
				if (!(res_144140 <= ((NI) 9))) goto LA3;
				nimln(1876, "system.nim");
				i_144097 = res_144140;
				nimln(18, "numple.nim");
				{
					if (i_144097 < 1 || i_144097 > 9) raiseIndexError();
					if (col < 1 || col > 9) raiseIndexError();
					if (!(matrix[(i_144097)- 1][(col)- 1] == num)) goto LA6;
					nimln(19, "numple.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA6: ;
				nimln(1895, "system.nim");
				TMP542 = addInt(res_144140, ((NI) 1));
				res_144140 = (NI)(TMP542);
			} LA3: ;
		}
	}
	{
		NI i_144108;
		NI res_144147;
		i_144108 = 0;
		nimln(1874, "system.nim");
		res_144147 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP543;
				if (!(res_144147 <= ((NI) 9))) goto LA10;
				nimln(1876, "system.nim");
				i_144108 = res_144147;
				nimln(23, "numple.nim");
				{
					if (row < 1 || row > 9) raiseIndexError();
					if (i_144108 < 1 || i_144108 > 9) raiseIndexError();
					if (!(matrix[(row)- 1][(i_144108)- 1] == num)) goto LA13;
					nimln(24, "numple.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
				nimln(1895, "system.nim");
				TMP543 = addInt(res_144147, ((NI) 1));
				res_144147 = (NI)(TMP543);
			} LA10: ;
		}
	}
	areax = 0;
	areay = 0;
	nimln(27, "numple.nim");
	LOC15 = 0;
	LOC15 = HEX2F_90804(col, ((NI) 3));
	LOC16 = 0;
	LOC16 = ceil(LOC15);
	TMP544 = mulInt(((NI) 3), ((NI) (((NF)(LOC16) - (NF)(1.0000000000000000e+00)))));
	areax = (NI)(TMP544);
	nimln(28, "numple.nim");
	LOC17 = 0;
	LOC17 = HEX2F_90804(row, ((NI) 3));
	LOC18 = 0;
	LOC18 = ceil(LOC17);
	TMP545 = mulInt(((NI) 3), ((NI) (((NF)(LOC18) - (NF)(1.0000000000000000e+00)))));
	areay = (NI)(TMP545);
	{
		NI i_144125;
		NI res_144167;
		i_144125 = 0;
		nimln(1874, "system.nim");
		res_144167 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP549;
				if (!(res_144167 <= ((NI) 3))) goto LA21;
				nimln(1876, "system.nim");
				i_144125 = res_144167;
				{
					NI j_144136;
					NI res_144161;
					j_144136 = 0;
					nimln(1874, "system.nim");
					res_144161 = ((NI) 1);
					{
						nimln(1875, "system.nim");
						while (1) {
							NI TMP548;
							if (!(res_144161 <= ((NI) 3))) goto LA24;
							nimln(1876, "system.nim");
							j_144136 = res_144161;
							nimln(32, "numple.nim");
							{
								NI TMP546;
								NI TMP547;
								TMP546 = addInt(i_144125, areay);
								if ((NI)(TMP546) < 1 || (NI)(TMP546) > 9) raiseIndexError();
								TMP547 = addInt(j_144136, areax);
								if ((NI)(TMP547) < 1 || (NI)(TMP547) > 9) raiseIndexError();
								if (!(matrix[((NI)(TMP546))- 1][((NI)(TMP547))- 1] == num)) goto LA27;
								nimln(33, "numple.nim");
								result = NIM_FALSE;
								goto BeforeRet;
							}
							LA27: ;
							nimln(1895, "system.nim");
							TMP548 = addInt(res_144161, ((NI) 1));
							res_144161 = (NI)(TMP548);
						} LA24: ;
					}
				}
				TMP549 = addInt(res_144167, ((NI) 1));
				res_144167 = (NI)(TMP549);
			} LA21: ;
		}
	}
	result = NIM_TRUE;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, recursivedfs_144213)(mtx144007 m, NI row, NI col, mtx144007* Result) {
	NI nextrow;
	NI nextcol;
	nimfr("recursiveDFS", "numple.nim")
{	nextrow = 0;
	nextcol = 0;
	nimln(42, "numple.nim");
	{
		if (!(row == ((NI) 10))) goto LA3;
		nimln(43, "numple.nim");
		viewmatrix_144013(m);
		nimln(44, "numple.nim");
		memcpy((void*)(*Result), (NIM_CONST void*)m, sizeof(mtx144007));
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP552;
		nimln(46, "numple.nim");
		if (!(col == ((NI) 9))) goto LA6;
		nimln(47, "numple.nim");
		TMP552 = addInt(row, ((NI) 1));
		nextrow = (NI)(TMP552);
		nimln(48, "numple.nim");
		nextcol = ((NI) 1);
	}
	goto LA1;
	LA6: ;
	{
		NI TMP553;
		nimln(50, "numple.nim");
		nextrow = row;
		nimln(51, "numple.nim");
		TMP553 = addInt(col, ((NI) 1));
		nextcol = (NI)(TMP553);
	}
	LA1: ;
	nimln(53, "numple.nim");
	{
		mtx144007 LOC13;
		nimln(349, "system.nim");
		if (row < 1 || row > 9) raiseIndexError();
		if (col < 1 || col > 9) raiseIndexError();
		if (!!((m[(row)- 1][(col)- 1] == ((NI) 0)))) goto LA11;
		nimln(54, "numple.nim");
		memset((void*)LOC13, 0, sizeof(LOC13));
		recursivedfs_144213(m, nextrow, nextcol, LOC13);
		memcpy((void*)(*Result), (NIM_CONST void*)LOC13, sizeof(mtx144007));
		goto BeforeRet;
	}
	goto LA9;
	LA11: ;
	{
		{
			NI i_144231;
			NI res_144488;
			i_144231 = 0;
			nimln(1874, "system.nim");
			res_144488 = ((NI) 1);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI TMP554;
					if (!(res_144488 <= ((NI) 9))) goto LA17;
					nimln(1876, "system.nim");
					i_144231 = res_144488;
					nimln(57, "numple.nim");
					{
						NIM_BOOL LOC20;
						mtx144007 matrix;
						mtx144007 matrix0;
						LOC20 = 0;
						LOC20 = checknum_144080(m, row, col, i_144231);
						if (!LOC20) goto LA21;
						memset((void*)matrix, 0, sizeof(matrix));
						nimln(58, "numple.nim");
						memcpy((void*)matrix, (NIM_CONST void*)m, sizeof(mtx144007));
						nimln(59, "numple.nim");
						if (row < 1 || row > 9) raiseIndexError();
						if (col < 1 || col > 9) raiseIndexError();
						matrix[(row)- 1][(col)- 1] = i_144231;
						memset((void*)matrix0, 0, sizeof(matrix0));
						nimln(60, "numple.nim");
						chckNil((void*)matrix0);
						memset((void*)matrix0, 0, sizeof(matrix0));
						recursivedfs_144213(matrix, nextrow, nextcol, matrix0);
						nimln(61, "numple.nim");
						{
							NIM_BOOL LOC25;
							nimln(349, "system.nim");
							LOC25 = 0;
							LOC25 = HEX3DHEX3D_144235(matrix0, matrix);
							if (!!(LOC25)) goto LA26;
							nimln(62, "numple.nim");
							memcpy((void*)(*Result), (NIM_CONST void*)matrix0, sizeof(mtx144007));
							goto BeforeRet;
						}
						LA26: ;
					}
					LA21: ;
					nimln(1895, "system.nim");
					TMP554 = addInt(res_144488, ((NI) 1));
					res_144488 = (NI)(TMP554);
				} LA17: ;
			}
		}
		nimln(63, "numple.nim");
		memcpy((void*)(*Result), (NIM_CONST void*)m, sizeof(mtx144007));
		goto BeforeRet;
	}
	LA9: ;
	}BeforeRet: ;
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_20843;
	exchandler_20843 = s;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_20843 = (*exchandler_20843).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_20842 = s;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_parseutilsDatInit000();
	HEX00_strutilsDatInit000();
	HEX00_timesDatInit000();
	HEX00_posixDatInit000();
	HEX00_osDatInit000();
	HEX00_mathDatInit000();
	numpleDatInit000();
	HEX00_parseutilsInit000();
	HEX00_strutilsInit000();
	HEX00_timesInit000();
	HEX00_posixInit000();
	HEX00_osInit000();
	HEX00_mathInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	numpleInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, numpleInit000)(void) {
	nimfr("numple", "numple.nim")
	{
		FILE* f;
		TSafePoint TMP556;
		nimln(67, "numple.nim");
		f = open_16817(((NimStringDesc*) &TMP555), ((NU8) 0), ((NI) -1));
		nimln(68, "numple.nim");
		pushSafePoint(&TMP556);
		TMP556.status = setjmp(TMP556.context);
		if (TMP556.status == 0) {
			mtx144007 sudoku;
			mtx144007 ans;
			memset((void*)sudoku, 0, sizeof(sudoku));
			{
				NI res_144551;
				nimln(1874, "system.nim");
				res_144551 = ((NI) 1);
				{
					nimln(1875, "system.nim");
					while (1) {
						NimStringDesc* line;
						NI TMP560;
						if (!(res_144551 <= ((NI) 9))) goto LA5;
						nimln(1876, "system.nim");
						i_144523 = res_144551;
						nimln(74, "numple.nim");
						line = readline_16916(f);
						{
							NI res_144545;
							j_144535 = 0;
							nimln(1874, "system.nim");
							res_144545 = ((NI) 1);
							{
								nimln(1875, "system.nim");
								while (1) {
									NI TMP557;
									NI TMP558;
									NI TMP559;
									if (!(res_144545 <= ((NI) 9))) goto LA8;
									nimln(1876, "system.nim");
									j_144535 = res_144545;
									nimln(76, "numple.nim");
									if (i_144523 < 1 || i_144523 > 9) raiseIndexError();
									if (j_144535 < 1 || j_144535 > 9) raiseIndexError();
									TMP557 = subInt(j_144535, ((NI) 1));
									if ((NU)((NI)(TMP557)) > (NU)(line->Sup.len)) raiseIndexError();
									TMP558 = subInt(((NI) (((NU8)(line->data[(NI)(TMP557)])))), ((NI) 48));
									sudoku[(i_144523)- 1][(j_144535)- 1] = (NI)(TMP558);
									nimln(1895, "system.nim");
									TMP559 = addInt(res_144545, ((NI) 1));
									res_144545 = (NI)(TMP559);
								} LA8: ;
							}
						}
						TMP560 = addInt(res_144551, ((NI) 1));
						res_144551 = (NI)(TMP560);
					} LA5: ;
				}
			}
			memset((void*)ans, 0, sizeof(ans));
			nimln(79, "numple.nim");
			chckNil((void*)ans);
			memset((void*)ans, 0, sizeof(ans));
			recursivedfs_144213(sudoku, ((NI) 1), ((NI) 1), ans);
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR);
		}
		{
			nimln(69, "numple.nim");
			fclose(f);
			nimln(70, "numple.nim");
			printf("%s\012", ((NimStringDesc*) &TMP561)? (((NimStringDesc*) &TMP561))->data:"nil");
		}
		if (TMP556.status != 0) reraiseException();
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, numpleDatInit000)(void) {
}

